### ISSUE TITLE
Bad Words not updating

### ISSUE THREAD

**Issue by SupremeMortal** [BukkitAI/AdvancedSwearDetection#2]
Learnt words are not being used till server restarts. They are added to the bad_words.txt but they are not being detected once immediately found.

**Comment by RookieTEC9** [comment]
The thread learns every 30 minutes and adds them. Try waiting 40 minutes and then tell us if the issue persists.

**Comment by RookieTEC9** [comment]
The thread learns every 30 minutes and adds them. Try waiting 40 minutes and then tell us if the issue persists.

**Comment by RookieTEC9** [comment]
The thread learns every 30 minutes and adds them. Try waiting 40 minutes and then tell us if the issue persists.

**Comment by JeremiU** [comment]
The thread learns every 30 minutes and adds them. Try waiting 40 minutes and then tell us if the issue persists.

**Comment by ArsenArsen** [comment]
I am aware of this issue, but quiet busy now, will work on trying to fix it. This should update immediately IIRC, and I havent checked on a while so it might be changed. As soon as I can I will be looking into maybe even recoding the AI system

**Comment by ArsenArsen** [comment]
Why was the issue closed @SupremeMortal? Is it working now?

**Comment by SupremeMortal** [comment]
Accident. :tongue: 
https://ci.potestas.xyz/job/AdvancedSwearDetection/
May come in useful

**Comment by ArsenArsen** [comment]
@SupremeMortal, it works? Also I'll use my CI server, maybe, and I need unit tests.
